### ISSUE TITLE
Unable to update radium

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/radium-docs#17]
Running `npm update radium` breaks:

```
> radium@0.18.0 postinstall /Users/kyle/Formidable/radium-docs/node_modules/radium
> cd lib || npm run lib

radium-docs@0.0.1 /Users/kyle/Formidable/radium-docs
└── UNMET PEER DEPENDENCY radium@0.18.0

npm WARN radium-grid@2.0.1 requires a peer of radium@^0.17.1 but none was installed.
npm ERR! code 1
```

**Comment by paulathevalley** [comment]
I see this, too, but not with `builder`. So, `builder run update-project` does not fail for me. Do you see the same behavior?

Additionally, based on my understanding of [`npm update`](https://docs.npmjs.com/cli/update), the task should be changed to `"update-project": "npm update radium"`, which will update just that package when there's a new version, otherwise it is left alone. And then, `npm run update-project` doesn't fail... 

As for `radium-grid`, there were plans to include it and a library of other `radium-*` type components on the docs site, but I think it's all still a little bit in flux.

**Comment by kylecesmat** [comment]
@paulathevalley running `builder run update-project` breaks as well. I'm not sure if it is an issue with this repo or with `radium-grid` and needing to add the latest radium as a peer-dep... But I'm also not sure where radium-grid is being referenced or why that module is included with this project.

**Comment by kylecesmat** [comment]
Removed radium-grid from package.json...
